### ISSUE TITLE
Legend left frame spine is invisible

### ISSUE THREAD

**Issue by yakir12** [JuliaPlots/Makie.jl#1349]
Running the first example in the [legend examples](https://makie.juliaplots.org/stable/examples/layoutables/legend/#legend_element_attributes) works but the left spine in the frame of the legend doesn't plot. This seems to be consistent in many other cases.
![a](https://user-images.githubusercontent.com/3281957/135458098-666db7ce-880a-46b3-99c5-ecf5c8b673b9.png)

I'm on `GLMakie v0.4.6`.

**Comment by jkrumbiegel** [comment]
Can you check if master has this problem? I fixed something related a couple weeks ago here https://github.com/JuliaPlots/Makie.jl/commit/dfb44f1bd1b3916b260f5011a135c65ed83bc1f0

**Comment by yakir12** [comment]
Yes, it does:
![a](https://user-images.githubusercontent.com/3281957/135459711-39355f08-6b4d-4027-8a1f-15dc09ac68b1.png)

This is from GLMakie v0.4.6 `https://github.com/JuliaPlots/Makie.jl.git:GLMakie#master`

**Comment by jkrumbiegel** [comment]
it's Makie that needs to be on master, not GLMakie

**Comment by yakir12** [comment]
Still a problem:
![a](https://user-images.githubusercontent.com/3281957/135463020-5974f2bc-64c2-49f2-a276-b5a80eef8083.png)

I'm on:
```julia
(jl_srBZ7r) pkg> st
      Status `/tmp/jl_srBZ7r/Project.toml`
  [e9467ef8] GLMakie v0.4.6
  [ee78f7c6] Makie v0.15.2 `https://github.com/JuliaPlots/Makie.jl.git#master`
```

**Comment by ffreyer** [comment]
See also #865.

Does the full frame become visible if you increase the linewidth?
```julia
f.content[2].elements[:frame].strokewidth[] = 2
```
What about pushing the lines forward?
```julia
translate!(f.content[2].elements[:frame].plots[2], 0, 0, 1)
```
Or setting overdraw true for the lines?
```julia
f.content[2].elements[:frame].plots[2].overdraw[] = true
```

**Comment by yakir12** [comment]
> See also #865.

Wow, yeah, seems very relevant. My WM is `i3`. I don't think `i3wm` is considered headless, but I don't have gnome or anything like that installed.

> Does the full frame become visible if you increase the linewidth?

no:
![linewidth](https://user-images.githubusercontent.com/3281957/135576790-938805ed-9554-43e6-b4e7-ad55d7eb0f6a.png)


> What about pushing the lines forward?

no:
![forward](https://user-images.githubusercontent.com/3281957/135576801-2449f677-f56c-4aae-b44b-ccf78b5d8e14.png)


> Or setting overdraw true for the lines?

no:
![overdraw](https://user-images.githubusercontent.com/3281957/135576805-d586ea6f-bc28-463d-8927-a3182d45dec5.png)

The code used to produce this:
```julia
using GLMakie

function example()
  f = Figure()

  Axis(f[1, 1])

  xs = 0:0.5:10
  ys = sin.(xs)
  lin = lines!(xs, ys, color = :blue)
  sca = scatter!(xs, ys, color = :red)
  sca2 = scatter!(xs, ys .+ 0.5, color = 1:length(xs), marker = :rect)

  Legend(f[1, 2],
         [lin, sca, [lin, sca], sca2],
         ["a line", "some dots", "both together", "rect markers"])

  return f
end

f = example()
f.content[2].elements[:frame].strokewidth[] = 2
save("linewidth.png", f)

f = example()
translate!(f.content[2].elements[:frame].plots[2], 0, 0, 1)
save("forward.png", f)

f = example()
f.content[2].elements[:frame].plots[2].overdraw[] = true
save("overdraw.png", f)
```
and my status is unchanged:
```julia
(makie) pkg> st
      Status `~/test/makie/Project.toml`
  [e9467ef8] GLMakie v0.4.6
  [ee78f7c6] Makie v0.15.2 `https://github.com/JuliaPlots/Makie.jl.git#master`
```

**Comment by ffreyer** [comment]
I get this issue on windows with the example from #1356. But only in the top legend, and not with the example from here. Changing linewidth, z translations, overdraw, adding points, scene.clear, visibility of other plots - none of those make the line visible for me. I also tried creating a second line plot with the same points. That is also missing the same line. 

What does make the line visible for me is translating the plot to the left. E.g. `translate!(f.content[2].elements[:frame].plots[2], -1, 0, 0)` following this example. This works with shifts > 0.165 for me, though the lines don't close correctly. Might be worth noting that the line points are all offset to .5 (for every legend as far as I can tell)

This is the figure from #1356 with lightgray background for the source scene, yellow background for the legend scene and every plot but the frame outline turned invisible.
![makie](https://user-images.githubusercontent.com/10947937/135731230-1e909f29-2a91-46f1-9ca7-b448669bc041.png)

**Comment by ffreyer** [comment]
Another thing that fixes this for me is removing the last point from the line plot.
```julia
# make figure ...

l = fig.content[2] # Legend
s = Makie.parent_scene(l.elements[:frame]) # Legend scene
lineplot = s.plots[1].plots[2]

lineplot[1][] # Point{2, Float32}[[10.5, 10.5], [85.5, 10.5], [85.5, 45.5], [10.5, 45.5], [10.5, 10.5], [10.5, 10.5]]
pop!(lineplot[1][])
lineplot[1][] # Point{2, Float32}[[10.5, 10.5], [85.5, 10.5], [85.5, 45.5], [10.5, 45.5], [10.5, 10.5]]

notify(lineplot[1])
```
after notify the left frame line becomes visible. The other legends from #1356 also have this point dublication but they work fine out of the box
